### ISSUE TITLE
high speed usb cdc acm + msd disconnected after few minutes

### ISSUE THREAD

**Issue by calism** [azure-rtos/usbx#102]
I would to like to have usb cdc acm + msd on one usb port.

In the device manager, I see my USB serial device. My mass storage device also appears in the Windows Explorator. However after a few minutes, the USB serial device disappears from the Device Manager and likewise the mass storage from Windows Explorator. So it looks like usb gets disconnected after few minutes.

Best regards

**Comment by xiaocq2001** [comment]
Since it's enumerated, the framework descriptors should be OK.
Do you have USB trace to check what happens when they disappear?
Will re-attaching make your device back (assuming board still power on when detaching USB)?

**Comment by calism** [comment]
No I don't have a usb trace.
- If I unplug the USB cable and plug in again, the USB Serial Device does not appear in the Device Manager.
- A reset needs to be performed to have the USB Serial Device in the Device Manager again.

**Comment by calism** [comment]
I have found an issue in my code and now everything is okay.
