### ISSUE TITLE
Usb pictbridge device and host questions

### ISSUE THREAD

**Issue by liuyuan0** [azure-rtos/usbx#110]
Greetings!

Is there any example for usb pictbridge device and host?
I have tried pictbridge-client-implementation and pictbridge-host-implementation in learn.microsoft.com.But I failed to build a workable project.
On the website,It says that I should call the function below:
'''
/* Activate the pictbridge dpshost. */

status = ux_pictbridge_dpshost_start(&pictbridge, pima);
if (status != UX_SUCCESS)
    return;
’‘’
How can I get the "pima"? 

Thank you.

**Comment by liuyuan0** [comment]
I have got  a workable example.
Thank you.

**Comment by BluesharkPD** [comment]
Hi @liuyuan0 can you please share with your project it can help me .
bluesharkpd@outlook.com
