### ISSUE TITLE
usbx_device_controllers

### ISSUE THREAD

**Issue by geek-slt** [azure-rtos/usbx#12]
Hello, may I have the usbx_host_controllers source code in the usbx\common folder, but there is no usbx_device_controllers file. Why?

**Comment by bhnaphade** [comment]
Hello,
Which board are you targeting for the project?

**Comment by geek-slt** [comment]
Hello，
My target MCU is STM32H743XIT6&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "azure-rtos/usbx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月14日(星期三) 晚上11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [azure-rtos/usbx] usbx_device_controllers (#12)





 
Hello,
 Which board are you targeting for the project?

**Comment by bhnaphade** [comment]
Hi,
ST has added USBX support for their STM32H7 family MCUs: https://www.st.com/en/embedded-software/x-cube-azrtos-h7.html
Please refer the link for examples and driver code.

**Comment by geek-slt** [comment]
I know that ST supports USBX and found relevant examples, but I don’t understand that USBX has a usbx_host_controllers file, but there is no usbx_device_controllers. Is it because the device_control is made by the chip manufacturer?

**Comment by geek-slt** [comment]
And the files in usbx_stm32_host_controllers are not consistent with usbx_host_controllers

**Comment by goldscott** [comment]
@geek-slt - Correct. Microsoft is not going to develop/maintain USBX drivers. Our partners like ST, NXP, Renesas, Microchip, etc. will develop and maintain USBX drivers. They know their devices much better than we do, so they can write drivers that take full advantage of all the hardware capabilities. See issue https://github.com/azure-rtos/usbx/issues/10 for a similar discussion.

**Comment by geek-slt** [comment]
Understand    Thankyou verymuch
