### ISSUE TITLE
usbx on renesas rx mcu

### ISSUE THREAD

**Issue by casju1** [azure-rtos/usbx#17]
Hi,
I am updating usbx from v5.9 to v6.1.6 on a Rx63 mcu. Currently i am using the "USBX host rx Controller" but is it possible to change it to ohci/ehci host controller? Because i can see in your latest release that you does not include rx controller files anymore. I have tried changing it to ehci but it doesn't seem to work.

**Comment by xiaocq2001** [comment]
Thanks for choosing USBX.
For the Renesas controller, we are still working on it and it will be available with Renesas release packet.

**Comment by casju1** [comment]
Thanks for the answer.
Where do i find the Renesas release packet and when do you expect it will be implemented?

**Comment by xiaocq2001** [comment]
I think Renesas will put his packets here: https://www2.renesas.cn/cn/en/design-support/software
They will put USBX and controller driver inside their packets, and they have their release plan.

Note if you have some previous packet that includes USBX 5.9 with host controller driver (HCD), you can try that HCD in USBX 6.
