### ISSUE TITLE
USB HID class : Composite device does not pass compliance tests.

### ISSUE THREAD

**Issue by t-yabui** [azure-rtos/usbx#25]
Hi,
I made a composite device that include multiple HID devices.
It is recognized by Windows and works. However it does not pass HID Tests with the USB2CV test tool.

* HID Class Descriptor Test
* HID Class GET/SET Idle Test
* HID Class Report Descriptor Test

The tests uses GET_DESCRIPTOR with ``wIndex`` parameter to get HID descriptors.
However current code does not use the parameter, therefore it does not return a HID descriptor except the first one.

I think that It should support ``request_index`` parameter as follows:

[ux_device_class_hid_descriptor_send.c.patch.txt](https://github.com/azure-rtos/usbx/files/6745214/ux_device_class_hid_descriptor_send.c.patch.txt)

**Comment by xiaocq2001** [comment]
Thanks for the feedback. We will fix in later updates.

**Comment by xiaocq2001** [comment]
Updated in 6.1.8

**Comment by t-yabui** [comment]
Thank you for handling the matter.
