### ISSUE TITLE
The ux_host_class_cdc_ecm not support process zero-length packet

### ISSUE THREAD

**Issue by zxslzx** [azure-rtos/usbx#26]
On linux we can use URB_ZERO_PACKET flag, but usbx doesn't seem to support similar operations.

**Comment by xiaocq2001** [comment]
Is there any special reason to use URB_ZERO_PACKET ?
USBX binds NetX and all network operations are handled by NetX or triggered by NetX operations, so I don't thing the API can be exactly same as linux API.

**Comment by zxslzx** [comment]
> Is there any special reason to use URB_ZERO_PACKET ?
> USBX binds NetX and all network operations are handled by NetX or triggered by NetX operations, so I don't thing the API can be exactly same as linux API.

On _Universal Serial Bus Communications Class Subclass Specification for Ethernet Control Model Devices_ 
![Snipaste_2021-08-04_11-18-33](https://user-images.githubusercontent.com/32009362/128116853-76c9b605-3ea3-499d-9627-427c1c31fb25.jpg)

**Comment by xiaocq2001** [comment]
In USBX 6.1.4 the segmentation is already handled.
