### ISSUE TITLE
Passed parameter types do not seem to match

### ISSUE THREAD

**Issue by zjm1060** [azure-rtos/usbx#3]
https://github.com/azure-rtos/usbx/blob/10ad1105ef70e8954e8beb684b409a5c8b5cedd1/common/usbx_host_classes/src/ux_host_class_cdc_acm_activate.c#L91

The trace found that the type of external incoming is UX_DEVICE *, which is forced to UX_INTERFACE * here

**Comment by yuxin-azrtos** [comment]
@zjm1060 thank you for the report. Our USB engineers will review the issue.  We may contact you for additional information.  This issue is closed. Feel free to reopen it if you have further questions.
