### ISSUE TITLE
Does USBX support multiple device type switching?

### ISSUE THREAD

**Issue by arilink** [azure-rtos/usbx#40]
The processor used in my project is STM32F105RBT6. I transplanted ThreadX and USBX for development. I want to know if USBX supports multiple device type switching. For example, USB is a normal USB device when it is working normally. When firmware update is required, enter USB DFU mode?

**Comment by xiaocq2001** [comment]
Host recognized device is actually from what device reported (descriptors), if your application start different USB framework on different triggers, host will see different devices.
So yes, USBX supports multiple device type switching.

**Comment by arilink** [comment]
I know this situation, I mean, for example, the currently running USB class is CDC. After receiving the command, can it be converted to HID through some operations without resetting the system?

**Comment by BlueShark7** [comment]
@xiaocq2001  how can i send a multiple audio isochrone packet in host app ?

**Comment by xiaocq2001** [comment]
@BlueShark7 Not sure what you mean for multiple audio isochrones packet, do you mean the usage of host audio class APIs?

**Comment by BlueShark7** [comment]
@xiaocq2001 yess i want to write to audio interface

**Comment by xiaocq2001** [comment]
@BlueShark7 sorry to reply late, can you create another issue to discuss since it's another topic, thanks.
