### ISSUE TITLE
USB cannot send data after sending some data

### ISSUE THREAD

**Issue by arilink** [azure-rtos/usbx#42]
I ported threadX and USBX on stm32f105rbt6. When I try to send some data through IN breakpoint, I can no longer send data but can accept data. The error of sending data is ux_device_class_hid_event_array_tail. Why is this?

**Comment by xiaocq2001** [comment]
It seems data is actually not sent, so the event queue is full.
I suggest to check your hardware settings especially FIFO of your interrupt IN endpoint.

**Comment by arilink** [comment]
Problem solved It's my own problem Thank you very much for your support and help
