### ISSUE TITLE
Does USBX support host class for CDC-ECM device or RNDIS device?

### ISSUE THREAD

**Issue by Gavyn-cheung** [azure-rtos/usbx#43]
Many IOT device using wireless network device to visit network,so USBX is or not support wireless device?

**Comment by MichaelZhg** [comment]
I want to use USBX to realize the network access of wireless network device on STM32 platform,using CDC-ECM or RNDIS device to access.

**Comment by goldscott** [comment]
USBX has a host CDC-ECM class here: https://github.com/azure-rtos/usbx/tree/master/common/usbx_host_classes/src

**Comment by MichaelZhg** [comment]
> USBX has a host CDC-ECM class here: https://github.com/azure-rtos/usbx/tree/master/common/usbx_host_classes/src

Yeah,I have see it ,about RNDIS device support have any plain?

**Comment by MichaelZhg** [comment]
> USBX has a host CDC-ECM class here: https://github.com/azure-rtos/usbx/tree/master/common/usbx_host_classes/src

Hi Glodscoot,
    Because we have a project that needs to use the STM32 USB host mode to drive the wireless network card, using the protocol mode of rndis or cdc-ecm, but there are too few reference examples of USBX, so we can only ask you for help.
    Look forward to your response,thank you!

**Comment by AndyW999** [comment]
I would like this too so I can connect to other RF devices that require an RNDIS Host to connect to.
It is a glaring omission by Microsoft...

**Comment by xiaocq2001** [comment]
There is no plan to support RNDIS on host side.

**Comment by AndyW999** [comment]
Disappointing but not really a surprise...
