### ISSUE TITLE
How about a callback when new event is received in receiver thread 

### ISSUE THREAD

**Issue by gawied** [azure-rtos/usbx#44]
First of all thank you vey much for adding support for optional OUT endpoint.

The current code structure calls for another thread to poll the ux_device_class_hid_receiver_event_get() function in order to be notified when new events are received data on the OUT endpoint.
How about adding a callback function, which can be part of the UX_DEVICE_CLASS_HID_RECEIVER structure, that will be called when the _ux_device_class_hid_receiver_thread determines that a new event was received. This will eliminate another polling thread and the system will be more event driven as well.

I certainly might have interpreted the new code incorrectly and would appreciate it if there are other ways than a polling thread to get notified of new received events.

**Comment by ayedmo** [comment]
@gawied same idee, i think that is helpful to add a callback when received data from Host.

**Comment by xiaocq2001** [comment]
Thanks for the suggestion, we will put that feature in our plan.

**Comment by gawied** [comment]
Thanks that will be great!

Any idea on the time span of your plan? What are we talking about here - weeks, months?

**Comment by yuxin-azrtos** [comment]
This callback will be added to the next release of Azure RTOS (towards the end of April 2022).

**Comment by gawied** [comment]
Thanks!
