### ISSUE TITLE
USBx移植到stm32f429bgt6平台出现很奇怪的问题

### ISSUE THREAD

**Issue by LiuChenghu** [azure-rtos/usbx#56]
![image](https://user-images.githubusercontent.com/30891935/157158317-1adb2233-ba4c-4fbc-9b26-25665b4999d1.png)
调试的时候发现，识别U盘之后，一会就会进入这个中断，然后U盘无法识别插拔动作了，参考的例程是Ux_Host_Msc，请问一下为什么会出现这样的现象，还有USBx的任务创建一定需要放在tx_application_define这里吗？我可以放在其他任务中创建吗？

**Comment by xiaocq2001** [comment]
It seems the code is in ST HAL code of HCD, you can refer to ST for support.
BTW, the interrupt callback seems to be invoked on port disable. If it's generated even if your device is connected, maybe you can check if there is physical connection issue.
Thread creation can be done anywhere except in interrupts, so you can create that in another thread/task.
