### ISSUE TITLE
OHCI_HC_PS_PRSC flag should be cleared in the ux_hCD_hoci_INTERRUPt_handler function

### ISSUE THREAD

**Issue by zhangjinxing** [azure-rtos/usbx#59]
I found that the OHCI_HC_PS_PRSC flag should be cleared in the ux_hcd_hoci_interrupt_handler function, otherwise the interrupt will continue。

![未命名图片](https://user-images.githubusercontent.com/8036731/159395967-3fe1c360-ed04-4f36-bbe9-2f579bb4e3f9.png)

But the following code needs to be modified
![未命名图片](https://user-images.githubusercontent.com/8036731/159396111-5b9b63a9-4493-4be6-af64-cd232b4dd4cb.png)

CPU：N32905 ARM926

**Comment by xiaocq2001** [comment]
How about disable HcInterruptEnable.RHSC when performing port reset, to avoid hanging in interrupts? It does lest change.

Another way with RTOS practice would be adding event flags (or semaphore) and wait events for the status change. In interrupt set event flags (or put semaphore) to wakeup pending thread that is doing reset.

**Comment by zhangjinxing** [comment]
Thanks！
