### ISSUE TITLE
USBx Emulation support on Windows

### ISSUE THREAD

**Issue by parthindia47** [azure-rtos/usbx#61]
Hi Everyone,
I wanted to know if there is USBx emulation support for windows ? Is it possible to use USBx similar to libusb ?

**Comment by xiaocq2001** [comment]
ux_hcd_sim_host* and ux_dcd_sim_device* files are emulation on host side and device side, which works together to make [demo_usbx.c](https://github.com/azure-rtos/usbx/blob/master/samples/demo_usbx.c) work on windows/linux.

But the simulation controller driver is not linked to windows USB driver, it's not possible to use USBx similar to libusb.

**Comment by xiaocq2001** [comment]
There is no driver to translate windows USB activities to USBX, it's not supported right now.
