### ISSUE TITLE
ux_network_driver

### ISSUE THREAD

**Issue by chengshuihang** [azure-rtos/usbx#62]
我想支持下NX_LINK_GET_STATUS，下面代码可以吗？
![76bfb1c6214075c2c16ae5d521b23bd](https://user-images.githubusercontent.com/45716763/164890442-34bc9d57-fc38-4422-8a5b-e0f02a1f85ab.png)
我发现关于ux_network_device_link_status的操作都是没有mutex的，在USB网卡插拔或者复位的时候不会对Netxduo造成破坏性影响吗？

另外ux_network_driver好像不支持IPV6，而且IPV6宏有个小错误
![793787ce365ecbb7eacb341b00eccce](https://user-images.githubusercontent.com/45716763/164890570-f1889d51-1992-4833-b29f-727848cdcef4.png)

**Comment by xiaocq2001** [comment]
For IPV6 support, `NX_ETHERNET_IPV6` should be 0x86DD (ref [here](https://github.com/azure-rtos/netxduo/blob/1eee883def078a91b8cd19159d1796e3a8862814/common/src/nx_ram_network_driver.c#L55)),
To support IPV6 incoming packet, additional change in `_ux_network_driver_packet_received` should be made to accept IPV6 packets (ref [here](https://github.com/azure-rtos/netxduo/blob/1eee883def078a91b8cd19159d1796e3a8862814/common/src/nx_ram_network_driver.c#L883)).

**Comment by chengshuihang** [comment]
是的，我修改了_ux_network_driver_packet_received和_ux_host_class_cdc_ecm_thread函数，让它们可以处理IPV6数据包。

**Comment by xiaocq2001** [comment]
network driver updated with IPV6 and some other fixes.
