### ISSUE TITLE
USBX drives CDC-ECM device as USB host

### ISSUE THREAD

**Issue by rk3399** [azure-rtos/usbx#63]
When the CDC-ECM device reports the MAC address to USBX, the whole system stops. I would like to know what is the reason for this.
My guess is that USBX is waiting for the CDC-ECM device to report the network connection status. But the CDC-ECM device doesn't do that. If my guess is correct, can you tell me where to find documentation on the CDC-ECM protocol, thanks!
(From Google Translate, the following is the original Chinese text.)

当CDC-ECM设备向USBX报告MAC地址后，整个系统便停止了。我想知道这是什么原因。
我的猜测是USBX在等待CDC-ECM设备报告网络连接状态。但CDC-ECM设备并没有这样做。如果我的猜测是对的，可以告诉我在哪里能找到关于CDC-ECM协议的文档吗，感谢！

**Comment by rk3399** [comment]
何时会从这个等待返回
![image](https://user-images.githubusercontent.com/58390397/166642521-9deeae6b-1909-46fb-a034-ec581b8bedd2.png)

**Comment by rk3399** [comment]
何时会从这个等待返回
![image](https://user-images.githubusercontent.com/58390397/166642752-c76f098f-b2dc-4f94-a377-5189d5f70793.png)

**Comment by xiaocq2001** [comment]
See ux_host_class_cdc_ecm_interrupt_notification.c, the semaphore is put when there is interrupt transfer notification about link state changes.

**Comment by xiaocq2001** [comment]
Please check [this file](https://usb.org/sites/default/files/CDC1.2_WMC1.1_012011.zip) for CDC ECM spec.

**Comment by rk3399** [comment]
> Please check [CDC1.2_WMC1.1_012011.zip on USB.org](https://usb.org/sites/default/files/CDC1.2_WMC1.1_012011.zip) for CDC ECM spec.
Thanks, this solved my doubt!
