### ISSUE TITLE
custom usb device with two interrupt endpoints

### ISSUE THREAD

**Issue by sw2mrc** [azure-rtos/usbx#65]
Hello!

I have played with HID and CDC-ACM device BX examples on STM32, and the project requires a custom class with two interrupt endpoints one IN EP and one OUT EP. Looking at the USBX API documentation (PDF version published on MSFT website) does not give clues on which APIs i can use to achieve this? any examples i can look at?

Thanks much in advance!

**Comment by xiaocq2001** [comment]
You can refer to ST's HID_CDC_ACM example, where HID mouse with IN EP is demoed.

HID optional interrupt OUT endpoint is supported by compile with UX_DEVICE_CLASS_HID_INTERRUPT_OUT_SUPPORT.
With it, you can add OUT EP descriptor to device framework and use ux_device_class_hid_read to read data from interrupt OUT endpoint (blocking current thread).
