### ISSUE TITLE
_ux_utility_memory_allocate调用方可以考虑字节对齐吗？

### ISSUE THREAD

**Issue by chengshuihang** [azure-rtos/usbx#69]
您好！_ux_utility_memory_allocate函数的调用方可以增加字节对齐的配置吗？我现在使用STM32H743，使用了USB DMA和高速缓存，因此我期望 传输的数据地址是32字节对齐的，并且这个数据缓冲区大小是32字节对齐的（实际传输的数据大小可以不是32字节倍数，但空间需要是32字节倍数，防止两种属性的数据在同一块高速缓存中）

**Comment by xiaocq2001** [comment]
Did you try the allocation with UX_ALIGN_32?

Another option, use MPU to setup a cache safe memory area for memory allocation, allocate cache safe memory to avoid caching issues.

**Comment by chengshuihang** [comment]
是的，我希望我可以指定UX_ALIGN_32分配，至于MPU管理非缓存内存方案，和我当前方案区别不是太大。

**Comment by chengshuihang** [comment]
或者我将UX_ALIGN_MIN修改为UX_ALIGN_32，可以吗？

**Comment by xiaocq2001** [comment]
Yes. You can try.

**Comment by xiaocq2001** [comment]
UX_ALIGN_MIN exported in ux_user_sample.h.

Closing.
