### ISSUE TITLE
如何在windows上使用rndis?

### ISSUE THREAD

**Issue by chengshuihang** [azure-rtos/usbx#70]
您好，假设我已经在设备上完成了rndis的适配，需要在windows上测试的话，pc上需要做哪些工作？RNDIS_Template.inf如何使用？

**Comment by xiaocq2001** [comment]
Get template here: `https://docs.microsoft.com/en-us/windows-hardware/drivers/network/remote-ndis-inf-template`, to create inf file
Replace `USB\VID_xxxx&PID_yyyy` with your VID and PID.
Make the inf digitally signed.

When connect your application to PC the device may appear as serial port, change the driver to the INF you created and signed.

**Comment by chengshuihang** [comment]
好的，谢谢！
