### ISSUE TITLE
Fix Build error with UX_HCD_EHCI_SPLIT_TRANSFER_ENABLE

### ISSUE THREAD

**Issue by luis-casado** [azure-rtos/usbx#8]
Enabling UX_HCD_EHCI_SPLIT_TRANSFER_ENABLE gives 12 build errors. Attached patch fix them.
Tested in i.MXRT1060.

Luis
[patch.diff.txt](https://github.com/azure-rtos/usbx/files/6102818/patch.diff.txt)

**Comment by xiaocq2001** [comment]
Thanks. Suggested patch will be taken into our updates.

**Comment by maxkunes** [comment]
I've recently tested this on MXRT1064 and this seems resolved now on the recent github version of usbx. The NXP sdk version is still outdated and requires the patch.

**Comment by yuxin-azrtos** [comment]
Close.
