### ISSUE TITLE
NXP MIMXRT1170 SRAM device storage

### ISSUE THREAD

**Issue by BluesharkPD** [azure-rtos/usbx#82]
Hi, I would like to develop an application device storage SRAM without RTOS. using a NXP MIMXRT1170. if i include usbx and filex there is warning of duplicated declaration  of Var in port. and declaration of var are not similar in tx/fx/ux port.

for example 
ULONG64 declared in fx 
typedef unsigned long long                      ULONG64;

ULONG64 declared in tx 
typedef unsigned long long                      ULONG64;

ULONG64 declared in ux
typedef uint64_t                                ULONG64;

**Comment by bhnaphade** [comment]
@BluesharkPD thank you for reporting the warning. we will check this internally and address this soon.

**Comment by BluesharkPD** [comment]
Any update about this (patch or expand to see details).??
