### ISSUE TITLE
duplicated definition UX_DEVICE_CLASS_AUDIO20_CONTROL_FREQUENCY_CHANGED

### ISSUE THREAD

**Issue by BluesharkPD** [azure-rtos/usbx#84]
Hi, there is a duplicated definition of UX_DEVICE_CLASS_AUDIO20_CONTROL_FREQUENCY_CHANGED in ux_device_class_audio10.h and ux_device_class_audio20.h

https://github.com/azure-rtos/usbx/blob/813361a875870d3c3c4ae7b830a54e0748e889e1/common/usbx_device_classes/inc/ux_device_class_audio10.h#L380

https://github.com/azure-rtos/usbx/blob/813361a875870d3c3c4ae7b830a54e0748e889e1/common/usbx_device_classes/inc/ux_device_class_audio20.h#L439

**Comment by xiaocq2001** [comment]
You are right. Thanks for pointing that out.

**Comment by xiaocq2001** [comment]
It will be fixed soon.
