### ISSUE TITLE
USBX send same HID descriptor data for different interface

### ISSUE THREAD

**Issue by HaoboGu** [azure-rtos/usbx#91]
Hello, I'm trying to use 2 interfaces in a HID class. My descriptor is like: 
<img width="438" alt="image" src="https://user-images.githubusercontent.com/8640918/229499824-b9767d7d-d3bc-455b-a177-eeebfad4e405.png">

There are two hid reports, using 2 interfaces. I enabled 2 interfaces by calling `ux_device_stack_class_register` twice, with different `ux_device_class_hid_parameter_report_address` and `interface_number`:
```c
  ux_device_stack_class_register(_ux_system_slave_class_hid_name, ux_device_class_hid_entry,
     0, 0, &parameter1);

  ux_device_stack_class_register(_ux_system_slave_class_hid_name, ux_device_class_hid_entry,
     0, 1, &parameter2);
```

 USBX sends correct configuration descriptor, but wrong HID descriptor data. 

The HID descriptor data for the first interface is correct, but for the second interface, USBX sends the same HID data with the length of second HID report. 

The correct HID descriptor data for the first interface: 
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/8640918/229501865-d66b42a2-c4c2-4ef1-b00e-3c1546ea56b9.png">

The wrong HID descriptor data for the second interface(this interface has two endpoints, this data appears twice):
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/8640918/229501864-f9497437-4632-45b5-aeba-ebeb59ca5e1a.png">

Except HID descriptor for the second interface(Ignore vid and pid):
<img width="503" alt="image" src="https://user-images.githubusercontent.com/8640918/229502202-c4ab36e9-0ec1-49fd-8934-54ae19f4a32b.png">

**Comment by xiaocq2001** [comment]
I'm not able to reproduce the issue in latest code.
Note in 6.1.8 release there is a fix about such issue: https://github.com/azure-rtos/usbx/releases/tag/v6.1.8_rel (HID descriptor search fix), file modification ([common/usbx_device_classes/src/ux_device_class_hid_descriptor_send.c](https://github.com/azure-rtos/usbx/commits/master/common/usbx_device_classes/src/ux_device_class_hid_descriptor_send.c))

**Comment by HaoboGu** [comment]
fixed by updating to latest version, thanks!
