### ISSUE TITLE
endpoint will mistakenly enter stall state while sending descritor 

### ISSUE THREAD

**Issue by xuzihan351** [azure-rtos/usbx#94]
ux_device_stack_descriptor_send:+404

      /* Ensure we have the correct language page.  */
      if (_ux_utility_short_get(string_framework) == request_index)

In some cases, host will send GET_STRING_DESCRTIPTOR setup packet with wIndex(the request_index var) == 0x0000, because of the code before, the stack will not be able to find a valid string and will generate a endpoint stall.

- USBX version: 6.2.1
- THREADX version:   6.2.1

**Comment by xiaocq2001** [comment]
As described in USB spec,
![image](https://user-images.githubusercontent.com/53201544/233238843-846653fe-1d85-4ade-a91a-23dd607706d3.png)

Zero wIndex case is not for string descriptor (reset to zero for other descriptors), we need to consider if it should be implemented.
